name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry virtual environment."

inputs:
   python-version:
     required: false
     description: "Python version to use"
     default: "3.11"
   poetry-options:
     required: false
     description: "Poetry options to pass"
     default: "--no-interaction"
   poetry-version:
     required: false
     description: "Poetry version to use"
     default: "2.1.1"
   working-directory:
     required: false
     description: "Working directory"
     default: "."

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true
        version: ${{ inputs.poetry-version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/.venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-options }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry install ${{ inputs.poetry-options }}
        touch .venv
